### ISSUE TITLE
locally built docker image doesn't work

### ISSUE THREAD

**Issue by eignatenkov** [Yorko/mlcourse.ai#370]
I've created docker image locally, using docker image build and then tried to run it like this:

`python run_docker_jupyter.py -t mlc_local`

got this:

```
Running command
docker run -it  --rm -p 5022:22 -p 4545:4545 -v "/home/egor/private/mlcourse.ai":/notebooks -w /notebooks mlc_local jupyter
Command: jupyter
[I 12:44:17.454 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/usr/lib/python3.5/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1379, in init_webapp
    self.jinja_environment_options,
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 251, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname
```

**Comment by Yorko** [comment]
It's not an Issue - the image works for thousands of people. 
You shall figure it out on your own, sorry. I'm not an expert in devops.

**Comment by eignatenkov** [comment]
It is not working because of the bug in the latest version of notebook package (5.7.0) which is being installed at the moment within the docker. 
The description of the bug is here: https://github.com/jupyter/docker-stacks/pull/721
I had to add this line
```
RUN pip3 install notebook==5.6.0
```
to Dockerfile to be able to build the image locally.

**Comment by Yorko** [comment]
Bumped into the same issue. Thanks, trying to resolve...

**Comment by Yorko** [comment]
Thanks a lot, this worked.

**Comment by stochasticB** [comment]
How can I stop getting these emails?

Thanks,
Bogdan

**Comment by Yorko** [comment]
I don't know - google it

**Comment by bhollan** [comment]
@stochasticB 

You can adjust your "Watching" settings and "Notification" settings.

https://help.github.com/articles/watching-and-unwatching-repositories/

![watching](https://user-images.githubusercontent.com/8443608/46809306-cc55c780-cd33-11e8-9ba8-f1ab52781879.png)

You can also mute this thread specifically if it's only this issue that's bothering you.

![mute](https://user-images.githubusercontent.com/8443608/46809305-cc55c780-cd33-11e8-829a-1b85c4c95347.png)
